# Generated by Django 4.1.2 on 2024-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('tipo', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'sugerencia'], [3, 'otros']])),
            ],
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.IntegerField(choices=[[0, 'juvenil'], [1, 'crec_personal'], [2, 'lit_chilena'], [3, 'novelas'], [4, 'poesia'], [5, 'novedades'], [6, 'ofertas']]),
        ),
    ]
