# Generated by Django 4.1.2 on 2024-06-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_nombre_genero_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
