# Generated by Django 4.1.2 on 2024-06-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_genero_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
