# Generated by Django 4.1.2 on 2024-06-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipoCon', models.IntegerField(choices=[[0, 'Consultas'], [1, 'Reclamos'], [2, 'Sugerencias']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
