# Generated by Django 5.0.1 on 2024-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('año_pub', models.CharField(max_length=4)),
                ('editorial', models.CharField(max_length=50)),
                ('encuadernacion', models.CharField(max_length=50)),
            ],
        ),
    ]
